#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Restore project files from a context dump generated by code_merger_GPT.py (e.g., project_context.txt).

How it works
- Parses blocks like:
  ============================================================
  FILE: path/to/file.py
  ============================================================
  <file content...>

Safety
- By default, creates a timestamped backup folder before overwriting.
- Refuses to write outside the project root.

Usage (run from your project root):
  python restore_from_context.py --context "project_context.txt"
  python restore_from_context.py --context "project_context (1).txt" --dry-run
  python restore_from_context.py --context "project_context.txt" --no-backup
"""

from __future__ import annotations

import argparse
import re
import time
from pathlib import Path
from typing import Dict, List, Tuple


# Match both 60 '=' lines and your newer '============================================================' lines.
# We accept any line with >= 20 '=' so it's robust if the delimiter length changes.
_HEADER_RE_BYTES = re.compile(
    rb"^={20,}\r?\nFILE:\s*(.+?)\r?\n={20,}\r?\n",
    re.MULTILINE,
)


def _is_within(child: Path, parent: Path) -> bool:
    """Return True if 'child' is inside 'parent' after resolving."""
    try:
        child_resolved = child.resolve()
        parent_resolved = parent.resolve()
        # Python 3.9+: Path.is_relative_to
        return child_resolved.is_relative_to(parent_resolved)  # type: ignore[attr-defined]
    except AttributeError:
        # Fallback for older versions
        try:
            child.resolve().relative_to(parent.resolve())
            return True
        except Exception:
            return False


def parse_context_bytes(blob: bytes) -> List[Tuple[str, bytes]]:
    """
    Return list of (relative_path_str, content_bytes) extracted from the context dump.
    """
    matches = list(_HEADER_RE_BYTES.finditer(blob))
    out: List[Tuple[str, bytes]] = []

    for i, m in enumerate(matches):
        raw_path = m.group(1).strip()
        rel_path = raw_path.decode("utf-8", errors="replace")

        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(blob)
        content = blob[start:end]

        # If the merger hit an error, it writes a marker. Skip those entries.
        if content.lstrip().startswith(b"[ERROR READING FILE:"):
            continue

        out.append((rel_path, content))

    return out


def backup_file(src: Path, backup_root: Path, rel_path: str) -> None:
    dst = backup_root / rel_path
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_bytes(src.read_bytes())  # preserve line endings precisely


def restore_files(
    entries: List[Tuple[str, bytes]],
    project_root: Path,
    do_backup: bool,
    dry_run: bool,
    backup_root: Path,
) -> Tuple[int, int, List[str]]:
    """
    Restore extracted entries to disk.
    Returns: (written_count, created_count, warnings)
    """
    written = 0
    created = 0
    warnings: List[str] = []

    # If duplicates exist, keep the LAST occurrence (most recent in dump).
    dedup: Dict[str, bytes] = {}
    for rel, content in entries:
        rel_norm = rel.replace("\\", "/").lstrip("/")

        # Safety: block absolute paths and parent traversal
        rel_path = Path(rel_norm)
        if rel_path.is_absolute() or ".." in rel_path.parts:
            warnings.append(f"SKIP (unsafe path): {rel}")
            continue

        dedup[str(rel_path)] = content

    for rel, content in sorted(dedup.items()):
        target = project_root / rel

        if not _is_within(target, project_root):
            warnings.append(f"SKIP (outside project root): {rel}")
            continue

        existed = target.exists()

        if dry_run:
            action = "OVERWRITE" if existed else "CREATE"
            print(f"[DRY-RUN] {action}: {rel}")
            continue

        # Backup existing file
        if existed and do_backup:
            try:
                backup_file(target, backup_root, rel)
            except Exception as e:
                warnings.append(f"BACKUP FAILED: {rel} -> {e}")

        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)

        written += 1
        if not existed:
            created += 1

    return written, created, warnings


def main() -> int:
    parser = argparse.ArgumentParser(description="Restore files from a project_context.txt dump.")
    parser.add_argument(
        "--context",
        default="project_context.txt",
        help="Path to the context dump file (default: project_context.txt).",
    )
    parser.add_argument(
        "--root",
        default=".",
        help="Project root directory to restore into (default: current directory).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Only print what would be overwritten/created; do not write anything.",
    )
    parser.add_argument(
        "--no-backup",
        action="store_true",
        help="Disable backup of existing files before overwrite.",
    )
    parser.add_argument(
        "--backup-dir",
        default=None,
        help="Custom backup directory. Default: _restore_backup/YYYYmmdd_HHMMSS inside project root.",
    )
    parser.add_argument(
        "--list",
        action="store_true",
        help="Only list file paths found in the dump and exit.",
    )

    args = parser.parse_args()
    project_root = Path(args.root).resolve()
    context_path = Path(args.context)

    if not context_path.exists():
        alt = project_root / args.context
        if alt.exists():
            context_path = alt
        else:
            print(f"❌ Context file not found: {args.context}")
            return 2

    blob = context_path.read_bytes()
    entries = parse_context_bytes(blob)

    if not entries:
        print("❌ No FILE blocks found. Is this the right dump format?")
        return 3

    if args.list:
        for rel, _ in entries:
            print(rel)
        print(f"\nTotal blocks: {len(entries)}")
        return 0

    ts = time.strftime("%Y%m%d_%H%M%S")
    do_backup = not args.no_backup

    if do_backup:
        if args.backup_dir:
            backup_root = Path(args.backup_dir)
            if not backup_root.is_absolute():
                backup_root = (project_root / backup_root).resolve()
        else:
            backup_root = (project_root / "_restore_backup" / ts).resolve()
        if not args.dry_run:
            backup_root.mkdir(parents=True, exist_ok=True)
    else:
        backup_root = (project_root / "_restore_backup" / ts).resolve()

    written, created, warnings = restore_files(
        entries=entries,
        project_root=project_root,
        do_backup=do_backup,
        dry_run=args.dry_run,
        backup_root=backup_root,
    )

    print("\n================ RESTORE SUMMARY ================")
    print(f"Project root : {project_root}")
    print(f"Context file : {context_path.resolve()}")
    print(f"Dry-run      : {args.dry_run}")
    print(f"Backup       : {'ON' if do_backup else 'OFF'}")
    if do_backup:
        print(f"Backup dir   : {backup_root}")
    if args.dry_run:
        print("Written      : 0 (dry-run)")
        print("Created      : 0 (dry-run)")
    else:
        print(f"Written      : {written}")
        print(f"Created      : {created}")
    if warnings:
        print("\nWarnings:")
        for w in warnings:
            print(" -", w)
    print("================================================\n")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
